export const ACTIONS = {
	CONNECT: 'connect',
	CONNECTION_ESTABLISHED: 'connection-established',
	NOTICE: 'notice',
	MESSAGE: 'message',
	ADD_MESSAGE: 'add-message',
	INIT_MESSAGES: 'init-messages',
	GET_MESSAGES: 'get-messages',
	USERS: 'users',
	DISCONNECT: 'disconnect',
	CALL_STATUS: 'call:status',
	CALL_SIGNAL: 'call:signal',
	CALL_READY_TO_JOIN: 'call:ready-to-join',
	CALL_INIT: 'call:init',
	CALL_LEAVE: 'call:leave',
	CALL_ENDED: 'call:ended',
}
